// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Samakan dengan yang benar-benar dipakai runtime (lihat config/prisma.ts) —
    // sebelumnya menunjuk ke DIRECT_URL yang tidak pernah ada di .env, bikin
    // `prisma generate`/`migrate`/`studio` gagal total untuk siapa pun yang
    // clone repo ini (bahkan `npm install` ikut gagal lewat postinstall).
    url: env("DATABASE_URL"),
  },
});
